name: appklittletits
description: "Sistema de Gestão para Barbearia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Banco de Dados
  supabase_flutter: ^2.12.2

  # Datas e Horários
  intl: ^0.20.2

  # Gerenciamento de Estado
  provider: ^6.1.5

  # Ícones
  font_awesome_flutter: ^10.10.0

  # Animações
  lottie: ^3.3.1
  animate_do: ^4.2.0

  # Sons
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/animations/